import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ip15.java
 *
 * Created on Sep 1, 2019, 3:49:57 PM
 */

/**
 *
 * @author Home
 */
public class ip15 extends javax.swing.JFrame {

    /** Creates new form ip15 */
    public ip15() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Algerian", 2, 18));
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("New Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 240, 140, 24);

        jLabel3.setFont(new java.awt.Font("Algerian", 2, 18));
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Password ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 180, 90, 24);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 120, 150, 22);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(240, 180, 150, 22);

        jLabel4.setFont(new java.awt.Font("Castellar", 2, 28));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Change the Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 60, 400, 37);

        jButton2.setBackground(new java.awt.Color(204, 51, 0));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 3, 18));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Change");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 300, 100, 40);

        jButton3.setBackground(new java.awt.Color(204, 51, 0));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 3, 18));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CANCEL");
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 300, 100, 40);

        jLabel5.setFont(new java.awt.Font("Algerian", 2, 18));
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Username ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 120, 88, 24);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(240, 240, 150, 22);

        jLabel6.setBackground(new java.awt.Color(255, 0, 102));
        jLabel6.setFont(new java.awt.Font("Algerian", 2, 30));
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Welcome Customer ");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 10, 280, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hqdefault.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 480, 360);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-496)/2, (screenSize.height-397)/2, 496, 397);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ip1","root","mysql");
            String user_id,password,new_password,sql;
            user_id=jTextField1.getText();
            password=new String(jPasswordField1.getPassword());
            new_password=new String(jPasswordField2.getPassword());
            sql="update customer set password='"+new_password+"' where username='"+user_id+"'and password='"+password+"'";
            Statement st=con.createStatement();
            int count=st.executeUpdate(sql);
            if(count>0)
             {
                JOptionPane.showMessageDialog(null,"Password is Changed");
                jPasswordField1.setText("");
                jPasswordField2.setText("");
              }
              
            else
            {
               JOptionPane.showMessageDialog(this,"Invalid UserName or Password");
               jPasswordField1.setText("");
               jPasswordField2.setText("");
            }
             }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"ERROR"+e.getMessage());
        }
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        new ip10().setVisible(true);
}//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ip15().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
