import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ip16.java
 *
 * Created on Jun 27, 2008, 4:15:10 AM
 */

/**
 *
 * @author Home
 */
public class ip16 extends javax.swing.JFrame {

    /** Creates new form ip16 */
    public ip16() {
        initComponents();
        jTextField5.setText("1");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 0, 102));
        jLabel2.setFont(new java.awt.Font("Algerian", 2, 30));
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Welcome Customer  ");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 20, 290, 39);

        jLabel8.setFont(new java.awt.Font("Castellar", 2, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Buy & Show Items");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 70, 320, 37);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SRNO", "ITEMS", "PRICES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 452, 190);

        jLabel5.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("     Items  Tables --");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 40, 180, 24);

        jButton10.setBackground(new java.awt.Color(51, 0, 255));
        jButton10.setFont(new java.awt.Font("Castellar", 2, 12));
        jButton10.setForeground(new java.awt.Color(255, 0, 0));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sweets.PNG"))); // NOI18N
        jButton10.setBorder(new javax.swing.border.MatteBorder(null));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(510, 70, 110, 60);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Comic Sans MS", 3, 12));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juices.PNG"))); // NOI18N
        jButton4.setBorder(new javax.swing.border.MatteBorder(null));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(510, 130, 110, 60);

        jButton9.setBackground(new java.awt.Color(51, 0, 255));
        jButton9.setFont(new java.awt.Font("Castellar", 2, 12));
        jButton9.setForeground(new java.awt.Color(255, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snacks.PNG"))); // NOI18N
        jButton9.setBorder(new javax.swing.border.MatteBorder(null));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(510, 190, 110, 70);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 3, 14));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture100.PNG"))); // NOI18N
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(510, 260, 130, 100);

        jLabel7.setFont(new java.awt.Font("Algerian", 2, 18));
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("Category");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 330, 150, 24);

        jTextField4.setEditable(false);
        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(290, 330, 150, 22);

        jLabel6.setFont(new java.awt.Font("Algerian", 2, 18));
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("Srno");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 370, 60, 24);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 370, 150, 22);

        jLabel3.setFont(new java.awt.Font("Algerian", 2, 18));
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Item Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 410, 100, 24);

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(290, 410, 150, 22);

        jLabel4.setFont(new java.awt.Font("Algerian", 2, 18));
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Net Amt.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 530, 100, 24);

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(290, 450, 150, 22);

        jButton5.setBackground(new java.awt.Color(204, 51, 0));
        jButton5.setFont(new java.awt.Font("Comic Sans MS", 3, 18));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Calculate Net Amt.");
        jButton5.setBorder(new javax.swing.border.MatteBorder(null));
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(480, 390, 190, 40);

        jTextField5.setEditable(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(290, 490, 150, 22);

        jLabel9.setFont(new java.awt.Font("Algerian", 2, 18));
        jLabel9.setForeground(new java.awt.Color(255, 51, 0));
        jLabel9.setText("Price");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 450, 70, 24);

        jLabel10.setFont(new java.awt.Font("Algerian", 2, 18));
        jLabel10.setForeground(new java.awt.Color(255, 51, 0));
        jLabel10.setText("Qty.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 490, 70, 24);

        jTextField6.setEditable(false);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(290, 530, 150, 22);

        jButton7.setBackground(new java.awt.Color(204, 51, 0));
        jButton7.setFont(new java.awt.Font("Comic Sans MS", 3, 18));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Purchase");
        jButton7.setBorder(new javax.swing.border.MatteBorder(null));
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(520, 440, 100, 40);

        jButton8.setBackground(new java.awt.Color(204, 51, 0));
        jButton8.setFont(new java.awt.Font("Comic Sans MS", 3, 18));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Cancel");
        jButton8.setBorder(new javax.swing.border.MatteBorder(null));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(520, 520, 100, 40);

        jTextField7.setEditable(false);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(170, 450, 70, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stars_space_galaxy_117958_3000x2000.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 600);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-701)/2, (screenSize.height-646)/2, 701, 646);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i=jTable1.getSelectedRow();
        DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
        jTextField1.setText(m.getValueAt(i, 0).toString());
        jTextField2.setText(m.getValueAt(i, 1).toString());
        jTextField3.setText(m.getValueAt(i, 2).toString());
        jButton7.setEnabled(false);
        jTextField6.setText("");
        jTextField5.setText("1");
        jButton5.setEnabled(true);
        JOptionPane.showMessageDialog(this,"PLEASE ENTER NO. OF QTY. OF "+jTextField2.getText());
        jTextField5.setEditable(true);
        
}//GEN-LAST:event_jTable1MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
        tm.setRowCount(0);
        jTextField4.setText("Sweets");

        try {
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ip1","root","mysql");
            Statement stmt=con.createStatement();
            String query="select * from sweets";
            ResultSet rs=stmt.executeQuery(query);

            while (rs.next()) {
                String Srno=rs.getString(1);
                String Sweets=rs.getString(2);
                String Price=rs.getString(3);
                Object[] ob1={Srno,Sweets,Price};
                tm.addRow(ob1);
                jTextField7.setText("per Kg");
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
        tm.setRowCount(0);
        jTextField4.setText("Juices");

        try {
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ip1","root","mysql");
            Statement stmt=con.createStatement();
            String query="select * from juices";
            ResultSet rs=stmt.executeQuery(query);

            while (rs.next()) {
                String Srno=rs.getString(1);
                String Juices=rs.getString(2);
                String Price=rs.getString(3);
                Object[] ob1={Srno,Juices,Price};
                tm.addRow(ob1);
                jTextField7.setText("per Glass");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
        tm.setRowCount(0);
        jTextField4.setText("Snacks");

        try {
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ip1","root","mysql");
            Statement stmt=con.createStatement();
            String query="select * from snacks";
            ResultSet rs=stmt.executeQuery(query);

            while (rs.next()) {
                String Srno=rs.getString(1);
                String Snacks=rs.getString(2);
                String Price=rs.getString(3);
                Object[] ob1={Srno,Snacks,Price};
                tm.addRow(ob1);
                jTextField7.setText("per Plate");
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
}//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
        tm.setRowCount(0);
        jTextField4.setText("Soft_Drinks");

        try {
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ip1","root","mysql");
            Statement stmt=con.createStatement();
            String query="select * from soft_drinks";
            ResultSet rs=stmt.executeQuery(query);

            while (rs.next()) {
                String Srno=rs.getString(1);
                String Soft_Drinks=rs.getString(2);
                String Price=rs.getString(3);
                Object[] ob1={Srno,Soft_Drinks,Price};
                tm.addRow(ob1);
                jTextField7.setText("per Glass");
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
}//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       double a=Double.parseDouble(jTextField3.getText());
       double b=Double.parseDouble(jTextField5.getText());
       double c=a*b;
       
       jTextField6.setText(""+c);
       
        int s= JOptionPane.showConfirmDialog(this, "ARE YOU SURE\nYOU WANT TO PURCHASE "+jTextField2.getText() +" !!","CONFIRM",JOptionPane.YES_OPTION,JOptionPane.NO_OPTION);
        if(s==JOptionPane.YES_OPTION){
            jButton5.setEnabled(false);
            jButton7.setEnabled(true);
           }
        else if(s == JOptionPane.NO_OPTION)
        {
            jTextField6.setText("");
            jTextField5.setText("1");
           }
        else if(s == JOptionPane.CLOSED_OPTION)
        {
            jTextField6.setText("");
            jTextField5.setText("1");
            }

      
     


}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      double a=Double.parseDouble(jTextField3.getText());
      double b=Double.parseDouble(jTextField5.getText());
      double c=a*b;
      jTextField6.setText(""+c);
      JOptionPane.showMessageDialog(this,"YOU HAVE TO PAY Rs.\t"+c+"\n\nTHANKS FOR VISITING.\nWE EXPECTED,\nTHAT YOU MUST VISIT OUR RESTAURANT AGAIN.");
      jTextField1.setText("");
      jTextField2.setText("");
      jTextField3.setText("");
      jTextField5.setText("1");
      jTextField6.setText("");
      jButton7.setEnabled(false);
      jTextField5.setEditable(false);


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
       
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.setVisible(false);
        new ip10().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ip16().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

}
