import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ip7.java
 *
 * Created on Aug 30, 2019, 8:03:01 PM
 */

/**
 *
 * @author Home
 */
public class ip7 extends javax.swing.JFrame {
    

    /** Creates new form ip7 */
    public ip7() {
        initComponents();

        


    

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 0, 102));
        jLabel2.setFont(new java.awt.Font("Algerian", 2, 30));
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Welcome Admin ");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 20, 230, 39);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SRNO", "ITEMS", "PRICES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 452, 190);

        jButton9.setBackground(new java.awt.Color(51, 0, 255));
        jButton9.setFont(new java.awt.Font("Castellar", 2, 12));
        jButton9.setForeground(new java.awt.Color(255, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snacks.PNG"))); // NOI18N
        jButton9.setBorder(new javax.swing.border.MatteBorder(null));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(490, 200, 120, 80);

        jButton10.setBackground(new java.awt.Color(51, 0, 255));
        jButton10.setFont(new java.awt.Font("Castellar", 2, 12));
        jButton10.setForeground(new java.awt.Color(255, 0, 0));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sweets.PNG"))); // NOI18N
        jButton10.setBorder(new javax.swing.border.MatteBorder(null));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(490, 80, 120, 60);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 3, 14));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture100.PNG"))); // NOI18N
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(490, 280, 140, 101);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Comic Sans MS", 3, 12));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juices.PNG"))); // NOI18N
        jButton4.setBorder(new javax.swing.border.MatteBorder(null));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(490, 140, 120, 60);

        jButton5.setBackground(new java.awt.Color(204, 51, 0));
        jButton5.setFont(new java.awt.Font("Comic Sans MS", 3, 18));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("CANCEL");
        jButton5.setBorder(new javax.swing.border.MatteBorder(null));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(210, 580, 100, 40);

        jLabel5.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("    Items  Tables --");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 40, 180, 24);

        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(290, 330, 150, 22);

        jLabel3.setFont(new java.awt.Font("Algerian", 2, 18));
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Item Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 410, 110, 24);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(290, 410, 150, 22);

        jLabel4.setFont(new java.awt.Font("Algerian", 2, 18));
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Price");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 450, 70, 24);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(290, 450, 150, 22);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 370, 150, 22);

        jButton2.setBackground(new java.awt.Color(204, 51, 0));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 3, 18));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 510, 110, 40);

        jLabel6.setFont(new java.awt.Font("Algerian", 2, 18));
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("Srno");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 370, 60, 24);

        jLabel7.setFont(new java.awt.Font("Algerian", 2, 18));
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("Category");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 330, 140, 24);

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Century", 3, 18));
        jRadioButton2.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButton2.setText("Add  Items");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(510, 410, 160, 31);

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Century", 3, 18));
        jRadioButton3.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButton3.setText("Update Price");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(510, 450, 160, 31);

        jButton6.setBackground(new java.awt.Color(204, 51, 0));
        jButton6.setFont(new java.awt.Font("Comic Sans MS", 3, 18));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Add");
        jButton6.setBorder(new javax.swing.border.MatteBorder(null));
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(90, 520, 110, 40);

        jLabel8.setFont(new java.awt.Font("Castellar", 2, 28));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Add & Update Details");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 70, 400, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stars_space_galaxy_117958_3000x2000.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 650);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-746)/2, (screenSize.height-688)/2, 746, 688);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

       DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
       tm.setRowCount(0);
       jTextField4.setText("Sweets");

       try {
       Class.forName("java.sql.DriverManager");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ip1","root","mysql");
       Statement stmt=con.createStatement();
       String query="select * from sweets";
       ResultSet rs=stmt.executeQuery(query);
      
       while (rs.next())
       {
       String Srno=rs.getString(1);
       String Sweets=rs.getString(2);
       String Price=rs.getString(3);
       Object[] ob1={Srno,Sweets,Price};
        tm.addRow(ob1);
       }
          }
      catch (Exception e)
        {
        JOptionPane.showMessageDialog(null,e.getMessage());
        }


}//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
       DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
       tm.setRowCount(0);
       jTextField4.setText("Juices");

       try {
       Class.forName("java.sql.DriverManager");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ip1","root","mysql");
       Statement stmt=con.createStatement();
       String query="select * from juices";
       ResultSet rs=stmt.executeQuery(query);
       
       while (rs.next())
       {
       String Srno=rs.getString(1);
       String Juices=rs.getString(2);
       String Price=rs.getString(3);
       Object[] ob1={Srno,Juices,Price};
        tm.addRow(ob1);
        }
          }
      catch (Exception e)
        {
        JOptionPane.showMessageDialog(null,e.getMessage());
        }
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      
       DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
       tm.setRowCount(0);
       jTextField4.setText("Snacks");

       try {
       Class.forName("java.sql.DriverManager");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ip1","root","mysql");
       Statement stmt=con.createStatement();
       String query="select * from snacks";
       ResultSet rs=stmt.executeQuery(query);
       
       while (rs.next())
       {
       String Srno=rs.getString(1);
       String Snacks=rs.getString(2);
       String Price=rs.getString(3);
       Object[] ob1={Srno,Snacks,Price};
        tm.addRow(ob1);
        }
          }
      catch (Exception e)
        {
        JOptionPane.showMessageDialog(null,e.getMessage());
        }
}//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
       DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
       tm.setRowCount(0);
       jTextField4.setText("Soft_Drinks");

       try {
       Class.forName("java.sql.DriverManager");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ip1","root","mysql");
       Statement stmt=con.createStatement();
       String query="select * from soft_drinks";
       ResultSet rs=stmt.executeQuery(query);

       while (rs.next())
       {
       String Srno=rs.getString(1);
       String Soft_Drinks=rs.getString(2);
       String Price=rs.getString(3);
       Object[] ob1={Srno,Soft_Drinks,Price};
        tm.addRow(ob1);
        }
          }
      catch (Exception e)
        {
        JOptionPane.showMessageDialog(null,e.getMessage());
        }
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        new ip6().setVisible(true);
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ip1","root","mysql");

            String srno , items,price ,sql;
            srno=jTextField1.getText();
            items=jTextField2.getText();
            price=jTextField3.getText();

            sql="update "+jTextField4.getText()+" set "+jTextField4.getText()+"='"+items+"',price='"+price+"'where srno="+srno;
            Statement st=con.createStatement();
            st.executeUpdate(sql);

            JOptionPane.showMessageDialog(this,"PRICE UPDATED\nClick on "+jTextField4.getText()+" to see Item Details");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            

        } catch(Exception e) {
            JOptionPane.showMessageDialog(this,"ERROR"+e.getMessage());
        }
}//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jButton6.setEnabled(true);
        jButton2.setEnabled(false);
        
}//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        jButton2.setEnabled(true);
        jButton6.setEnabled(false);
}//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      try {
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ip1","root","mysql");
            String srno,item,price,sql;
            srno=jTextField1.getText();
            item=jTextField2.getText();
            price=jTextField3.getText();

            sql="insert into "+jTextField4.getText()+" values('"+srno+"','"+item+"','"+price+"')";
            Statement st=con.createStatement();
            st.executeUpdate(sql);

               JOptionPane.showMessageDialog(this,"ITEM ADDED\nClick on "+jTextField4.getText()+" to see Item Details");
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
          }
      catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"ERROR"+e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      int i=jTable1.getSelectedRow();
      DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
      jTextField1.setText(m.getValueAt(i, 0).toString());
      jTextField2.setText(m.getValueAt(i, 1).toString());
      jTextField3.setText(m.getValueAt(i, 2).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ip7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
